# Generated by Django 5.1.4 on 2024-12-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorytree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
